#!/bin/sh -ex
IFS=
REPO=github.com/elves/elvish
: ${GOPATH:=/data/go}; export GOPATH
: ${PUBLISH_DIR:=/data/html}

go get -u $REPO
make -C $GOPATH/src/$REPO/website PUBLISH_DIR=$PUBLISH_DIR/ genblog publish
