#!/bin/sh -ex
IFS=
REPO=github.com/elves/elvish
: ${GOPATH:=/data/go}; export GOPATH
: ${PUBLISH_DIR:=/data/html}
: ${BIN_DIR:=/data/bin}

go get -u $REPO
make -C $GOPATH/src/$REPO/_website PUBLISH_DIR=$PUBLISH_DIR/ genblog publish
make -C $GOPATH/src/$REPO BIN_DIR=$BIN_DIR VERSION_SUFFIX=HEAD buildall
