#!/bin/sh -ex
: ${SRC_DIR:=/data/src}
: ${HTML_DIR:=/data/html}
: ${BIN_DIR:=/data/bin}

if ! test -d $SRC_DIR/.git; then
    git clone https://github.com/elves/elvish $SRC_DIR
fi

(
cd $SRC_DIR
git restore .
git pull --ff-only

# Website
make -C ./website PUBLISH_DIR=$HTML_DIR/ -B publish
# Docset
make -C ./website docset
mkdir $HTML_DIR/ref/docset
tar -C ./website -cvzf $HTML_DIR/ref/docset/Elvish.tgz Elvish.docset
cat > $HTML_DIR/ref/docset/Elvish.xml <<EOF
<entry>
  <version>$(date +%Y-%m-%d)-$(git rev-parse HEAD)</version>
  <url>https://elv.sh/ref/docset/Elvish.tgz</url>
</entry>
EOF
# Binaries
ELVISH_REPRODUCIBLE=dev ./tools/buildall.sh . $BIN_DIR HEAD
)
`dirname $0`/update-index
