#!/bin/sh -ex
: ${BIN_DIR:=/data/bin}

TAG=$1
if printf '%s\n' "$TAG" | grep '-dev$'; then
    echo 'Not building for *-dev' tag
    exit
fi

SRC_DIR=`mktemp -d`
trap "rm -rf $SRC_DIR" exit
git clone --depth=1 --branch="$TAG" https://github.com/elves/elvish $SRC_DIR

ELVISH_BUILD_VARIANT=official $SRC_DIR/tools/buildall.sh . $BIN_DIR $TAG

`dirname $0`/update-index
